model:
  target: ldm.models.diffusion.ddpm_ips.Fin_Aug_diffusion  
  params:
    learning_rate: 1.5e-05
    linear_start: 0.00085
    linear_end: 0.0120
    log_every_t: 200
    timesteps: 1000
    image_size: 64
    channels: 1
    monitor: val/loss_simple_ema
    use_ema: False
    first_stage_key: "image"
    scale_factor: 0.18215  
    cond_stage_key: "caption"
    cond_stage_trainable: false
    conditioning_key: 'concat'
    #parameterization: "x0"
    #only_mid_control: False 
    #control_key: "hint" 


    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel_Fin_Aug.UNet_FA
      params:
        image_size: 32 
        in_channels: 1
        out_channels: 1
        model_channels: 160
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 1
        channel_mult: [ 1, 2,4]
        num_heads: 8
        transformer_depth: 1
        use_checkpoint: True
        legacy: False
        num_classes: 20
    
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder